/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * By Luke Jang
 * 2021-05-06
 * Made a multiple choice program 
 * * Note that the program may look different depending on the monitor size
 * * So please take a look at "design" to see what the result is suppose to look like if you have same monitor size with me
 */
public class test extends javax.swing.JFrame {

    
    

    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        lblTitle = new javax.swing.JLabel();
        lblDiscrip1 = new javax.swing.JLabel();
        lblDiscrip2 = new javax.swing.JLabel();
        lblQ1 = new javax.swing.JLabel();
        lblQ1A = new javax.swing.JLabel();
        lblQ1B = new javax.swing.JLabel();
        lblQ1C = new javax.swing.JLabel();
        lblQ1D = new javax.swing.JLabel();
        txtQ1Ans = new javax.swing.JTextField();
        lblResult1 = new javax.swing.JLabel();
        lblQ2 = new javax.swing.JLabel();
        lblQ2A = new javax.swing.JLabel();
        lblQ2B = new javax.swing.JLabel();
        lblQ2C = new javax.swing.JLabel();
        lblQ2D = new javax.swing.JLabel();
        txtQ2Ans = new javax.swing.JTextField();
        lblResult2 = new javax.swing.JLabel();
        lblQ3 = new javax.swing.JLabel();
        lblQ3A = new javax.swing.JLabel();
        lblQ3B = new javax.swing.JLabel();
        lblQ3C = new javax.swing.JLabel();
        lblQ3D = new javax.swing.JLabel();
        txtQ3Ans = new javax.swing.JTextField();
        lblResult3 = new javax.swing.JLabel();
        lblQ4 = new javax.swing.JLabel();
        lblQ4A = new javax.swing.JLabel();
        lblQ4B = new javax.swing.JLabel();
        lblQ4C = new javax.swing.JLabel();
        lblQ4D = new javax.swing.JLabel();
        txtQ4Ans = new javax.swing.JTextField();
        lblResult4 = new javax.swing.JLabel();
        lblQ5 = new javax.swing.JLabel();
        lblQ5A = new javax.swing.JLabel();
        lblQ5B = new javax.swing.JLabel();
        lblQ5C = new javax.swing.JLabel();
        lblQ5D = new javax.swing.JLabel();
        txtQ5Ans = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        lblResult5 = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblIncorrect = new javax.swing.JLabel();
        lblPercentage = new javax.swing.JLabel();
        lblCorrectValue = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblPercentageValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(195, 226, 191));
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(37, 121, 125));
        panel1.setLayout(null);

        panel2.setBackground(new java.awt.Color(106, 173, 176));
        panel2.setLayout(null);

        panel3.setBackground(new java.awt.Color(159, 227, 192));
        panel3.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Myanmar Text", 1, 36)); // NOI18N
        lblTitle.setText("Multiple Choice Quiz");
        panel3.add(lblTitle);
        lblTitle.setBounds(270, 20, 400, 50);

        lblDiscrip1.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        lblDiscrip1.setText("Please enter the correct answer in the text field and press submit.");
        panel3.add(lblDiscrip1);
        lblDiscrip1.setBounds(10, 90, 580, 30);

        lblDiscrip2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        lblDiscrip2.setText("Please enter the letter, not the full answer. (Ex. A)");
        panel3.add(lblDiscrip2);
        lblDiscrip2.setBounds(10, 120, 490, 30);

        lblQ1.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ1.setText("What is 4+100?");
        panel3.add(lblQ1);
        lblQ1.setBounds(10, 180, 90, 25);

        lblQ1A.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ1A.setText("A. 103");
        panel3.add(lblQ1A);
        lblQ1A.setBounds(10, 210, 36, 25);

        lblQ1B.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ1B.setText("B. 96");
        panel3.add(lblQ1B);
        lblQ1B.setBounds(170, 210, 28, 25);

        lblQ1C.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ1C.setText("C. 0");
        panel3.add(lblQ1C);
        lblQ1C.setBounds(10, 260, 22, 25);

        lblQ1D.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ1D.setText("D. none of the above");
        panel3.add(lblQ1D);
        lblQ1D.setBounds(170, 260, 123, 25);

        txtQ1Ans.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        txtQ1Ans.setText("Enter Your Answer Here");
        txtQ1Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ1AnsActionPerformed(evt);
            }
        });
        panel3.add(txtQ1Ans);
        txtQ1Ans.setBounds(10, 300, 145, 31);

        lblResult1.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblResult1.setText("Result");
        panel3.add(lblResult1);
        lblResult1.setBounds(10, 340, 430, 25);

        lblQ2.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ2.setText("What is the 7th element on the periodic table?");
        panel3.add(lblQ2);
        lblQ2.setBounds(10, 400, 269, 25);

        lblQ2A.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ2A.setText("A. Carbon");
        panel3.add(lblQ2A);
        lblQ2A.setBounds(10, 430, 58, 25);

        lblQ2B.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ2B.setText("B.Nitrogen");
        panel3.add(lblQ2B);
        lblQ2B.setBounds(160, 430, 62, 25);

        lblQ2C.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ2C.setText("C. Oxygen");
        panel3.add(lblQ2C);
        lblQ2C.setBounds(10, 480, 59, 25);

        lblQ2D.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ2D.setText("D. Fluorine");
        panel3.add(lblQ2D);
        lblQ2D.setBounds(160, 480, 62, 25);

        txtQ2Ans.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        txtQ2Ans.setText("Enter Your Answer Here");
        txtQ2Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ2AnsActionPerformed(evt);
            }
        });
        panel3.add(txtQ2Ans);
        txtQ2Ans.setBounds(10, 520, 145, 31);

        lblResult2.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblResult2.setText("Result:");
        panel3.add(lblResult2);
        lblResult2.setBounds(10, 560, 430, 25);

        lblQ3.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ3.setText("Who is the first prime minister of Canada?");
        panel3.add(lblQ3);
        lblQ3.setBounds(450, 180, 250, 25);

        lblQ3A.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ3A.setText("A. Terry Fox");
        panel3.add(lblQ3A);
        lblQ3A.setBounds(450, 210, 90, 25);

        lblQ3B.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ3B.setText("B. John A. Macdonald");
        panel3.add(lblQ3B);
        lblQ3B.setBounds(600, 210, 140, 25);

        lblQ3C.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ3C.setText("C. Drake");
        panel3.add(lblQ3C);
        lblQ3C.setBounds(450, 260, 60, 25);

        lblQ3D.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ3D.setText("D. None of the above");
        panel3.add(lblQ3D);
        lblQ3D.setBounds(600, 260, 130, 25);

        txtQ3Ans.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        txtQ3Ans.setText("Enter Your Answer Here");
        panel3.add(txtQ3Ans);
        txtQ3Ans.setBounds(450, 300, 145, 31);

        lblResult3.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblResult3.setText("Result:");
        panel3.add(lblResult3);
        lblResult3.setBounds(450, 340, 440, 25);

        lblQ4.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ4.setText("What does WORA stand for?");
        panel3.add(lblQ4);
        lblQ4.setBounds(450, 400, 220, 25);

        lblQ4A.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ4A.setText("A. Write Once Run Anywhere");
        panel3.add(lblQ4A);
        lblQ4A.setBounds(450, 430, 180, 25);

        lblQ4B.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ4B.setText("B. Whale Of Ruined Atlantis");
        panel3.add(lblQ4B);
        lblQ4B.setBounds(680, 430, 180, 25);

        lblQ4C.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ4C.setText("C. Wonka Oomba Roomba Aka");
        panel3.add(lblQ4C);
        lblQ4C.setBounds(450, 480, 190, 25);

        lblQ4D.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ4D.setText("D. None of the above");
        panel3.add(lblQ4D);
        lblQ4D.setBounds(680, 480, 180, 25);

        txtQ4Ans.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        txtQ4Ans.setText("Enter Your Answer Here");
        txtQ4Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ4AnsActionPerformed(evt);
            }
        });
        panel3.add(txtQ4Ans);
        txtQ4Ans.setBounds(450, 520, 145, 31);

        lblResult4.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblResult4.setText("Result:");
        panel3.add(lblResult4);
        lblResult4.setBounds(450, 560, 430, 25);

        lblQ5.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ5.setText("Who is AY Jackson?");
        panel3.add(lblQ5);
        lblQ5.setBounds(10, 650, 220, 25);

        lblQ5A.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ5A.setText("A. A singer");
        panel3.add(lblQ5A);
        lblQ5A.setBounds(10, 680, 120, 25);

        lblQ5B.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ5B.setText("B. A canadian artist");
        panel3.add(lblQ5B);
        lblQ5B.setBounds(170, 680, 150, 25);

        lblQ5C.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ5C.setText("C. A computer scienctist");
        panel3.add(lblQ5C);
        lblQ5C.setBounds(10, 730, 150, 25);

        lblQ5D.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblQ5D.setText("D. None of the above");
        panel3.add(lblQ5D);
        lblQ5D.setBounds(170, 730, 150, 25);

        txtQ5Ans.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        txtQ5Ans.setText("Enter Your Answer Here");
        panel3.add(txtQ5Ans);
        txtQ5Ans.setBounds(10, 770, 145, 31);

        btnCalculate.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        btnCalculate.setText("Submit");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        panel3.add(btnCalculate);
        btnCalculate.setBounds(570, 640, 100, 50);

        lblResult5.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblResult5.setText("Result:");
        panel3.add(lblResult5);
        lblResult5.setBounds(10, 810, 430, 25);

        lblCorrect.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblCorrect.setText("Number of questions answered correctly:");
        panel3.add(lblCorrect);
        lblCorrect.setBounds(450, 720, 250, 25);

        lblIncorrect.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblIncorrect.setText("Number of questions answered incorrectly:");
        panel3.add(lblIncorrect);
        lblIncorrect.setBounds(450, 760, 260, 25);

        lblPercentage.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblPercentage.setText("Percentage of questions answered correctly:");
        panel3.add(lblPercentage);
        lblPercentage.setBounds(450, 800, 270, 25);

        lblCorrectValue.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblCorrectValue.setText("0");
        panel3.add(lblCorrectValue);
        lblCorrectValue.setBounds(770, 720, 7, 25);

        lblIncorrectValue.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblIncorrectValue.setText("0");
        panel3.add(lblIncorrectValue);
        lblIncorrectValue.setBounds(770, 760, 20, 25);

        lblPercentageValue.setFont(new java.awt.Font("Myanmar Text", 0, 13)); // NOI18N
        lblPercentageValue.setText("0%");
        panel3.add(lblPercentageValue);
        lblPercentageValue.setBounds(770, 800, 50, 25);

        panel2.add(panel3);
        panel3.setBounds(10, 10, 910, 920);

        panel1.add(panel2);
        panel2.setBounds(20, 20, 930, 950);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 970, 1030);

        pack();
    }// </editor-fold>                        

    private void txtQ1AnsActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtQ2AnsActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtQ4AnsActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {                                             
        ////Declaring variable, and constants
        
        //declaring variable for user answers and giving the corresponding value to the. The numbers indicates question number
        String userAns1 = txtQ1Ans.getText();
        String userAns2 = txtQ2Ans.getText();
        String userAns3 = txtQ3Ans.getText();
        String userAns4 = txtQ4Ans.getText();
        String userAns5 = txtQ5Ans.getText();
        
        //declaring constant for the correct answers and the wrong answers
        final String CORRECT = "Result: Congratulation! You are correct!!";
        final String Q1_INCORRECT = "Result: Incorrect! Make sure you check the plus and minus properly!"; 
        final String Q2_INCORRECT = "Result: Incorrect! Hey periodic table might help!";
        final String Q3_INCORRECT = "Result: Incorrect! Maybe you should listen to history class.";
        final String Q4_INCORRECT = "Result: Incorrect! Remember Java can work on any ios platform :D";
        final String Q5_INCORRECT = "Result: Incorrect! I heard that AY Jackson Secondary School is full of artists..";
        
        //variables/constant necessary to make calculations
        final double TOTAL_QUESTIONS = 5;
        double correctCounter = 0;
        double incorrect;
        double percentageCorrect;
        
        
        
        ////Checking if the answers are right and giving the feedbacks
        if ((userAns1.equals("D")) || userAns1.equals("d")){
            lblResult1.setText(String.valueOf(CORRECT));
            correctCounter = correctCounter + 1;
        }
        else {
            lblResult1.setText(String.valueOf(Q1_INCORRECT));
        }
        
        if ((userAns2.equals("B")) || userAns2.equals("b")){
            lblResult2.setText(String.valueOf(CORRECT));
            correctCounter = correctCounter + 1;
        }
        else {
            lblResult2.setText(String.valueOf(Q2_INCORRECT));
        }
        
        if ((userAns3.equals("B")) || userAns3.equals("b")){
            lblResult3.setText(String.valueOf(CORRECT));
            correctCounter = correctCounter + 1;
        }
        else {
            lblResult3.setText(String.valueOf(Q3_INCORRECT));
        }
        
        if ((userAns4.equals("A")) || userAns4.equals("a")){
            lblResult4.setText(String.valueOf(CORRECT));
            correctCounter = correctCounter + 1;
        }
        else {
            lblResult4.setText(String.valueOf(Q4_INCORRECT));
        }
        
        if ((userAns5.equals("B")) || userAns5.equals("b")){
            lblResult5.setText(String.valueOf(CORRECT));
            correctCounter = correctCounter + 1;
        }
        else {
            lblResult5.setText(String.valueOf(Q5_INCORRECT));
        }
        
        ////caluculating values
        incorrect = TOTAL_QUESTIONS - correctCounter;
        percentageCorrect = (correctCounter/TOTAL_QUESTIONS) * 1000; //times by 1000 since rounding to one decimal
        percentageCorrect = Math.round(percentageCorrect);
        percentageCorrect = percentageCorrect/10;
        
        ////displaying values
        lblCorrectValue.setText(String.valueOf((int)correctCounter));
        lblIncorrectValue.setText(String.valueOf((int)incorrect));
        lblPercentageValue.setText(String.valueOf(percentageCorrect + "%"));
        
        
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblDiscrip1;
    private javax.swing.JLabel lblDiscrip2;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblPercentage;
    private javax.swing.JLabel lblPercentageValue;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ1A;
    private javax.swing.JLabel lblQ1B;
    private javax.swing.JLabel lblQ1C;
    private javax.swing.JLabel lblQ1D;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ2A;
    private javax.swing.JLabel lblQ2B;
    private javax.swing.JLabel lblQ2C;
    private javax.swing.JLabel lblQ2D;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQ3A;
    private javax.swing.JLabel lblQ3B;
    private javax.swing.JLabel lblQ3C;
    private javax.swing.JLabel lblQ3D;
    private javax.swing.JLabel lblQ4;
    private javax.swing.JLabel lblQ4A;
    private javax.swing.JLabel lblQ4B;
    private javax.swing.JLabel lblQ4C;
    private javax.swing.JLabel lblQ4D;
    private javax.swing.JLabel lblQ5;
    private javax.swing.JLabel lblQ5A;
    private javax.swing.JLabel lblQ5B;
    private javax.swing.JLabel lblQ5C;
    private javax.swing.JLabel lblQ5D;
    private javax.swing.JLabel lblResult1;
    private javax.swing.JLabel lblResult2;
    private javax.swing.JLabel lblResult3;
    private javax.swing.JLabel lblResult4;
    private javax.swing.JLabel lblResult5;
    private javax.swing.JLabel lblTitle;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JTextField txtQ1Ans;
    private javax.swing.JTextField txtQ2Ans;
    private javax.swing.JTextField txtQ3Ans;
    private javax.swing.JTextField txtQ4Ans;
    private javax.swing.JTextField txtQ5Ans;
    // End of variables declaration                   
}
